/*
 * Created on 2026-05-24 ( 17:03:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.EntityGraph;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.DocumentosrequisitoprogramacohorteEntity;

@Repository
public interface DocumentosrequisitoprogramacohorteRepository extends JpaRepository<DocumentosrequisitoprogramacohorteEntity, Integer> {

	@EntityGraph(type = EntityGraph.EntityGraphType.FETCH)
	List<DocumentosrequisitoprogramacohorteEntity> findByIdCohorte(Integer idCohorte);

	@Query("SELECT dpc FROM DocumentosrequisitoprogramacohorteEntity dpc JOIN FETCH dpc.documentosrequisitoprograma WHERE dpc.idCohorte = :idCohorte")
	List<DocumentosrequisitoprogramacohorteEntity> findByIdCohorteWithRequisito(@Param("idCohorte") Integer idCohorte);
}
