/*
 * Created on 2026-05-24 ( 17:03:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.EntityGraph;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import ufps.edu.co.persistence.entities.DocumentoEntity;

@Repository
public interface DocumentoRepository extends JpaRepository<DocumentoEntity, Integer> {

	@Override
	@EntityGraph(attributePaths = {"estadodocumento"}, type = EntityGraph.EntityGraphType.FETCH)
	Optional<DocumentoEntity> findById(Integer id);

	@EntityGraph(attributePaths = {"estadodocumento"}, type = EntityGraph.EntityGraphType.FETCH)
	@Query("SELECT d FROM DocumentoEntity d WHERE d.idAspirante = :idAspirante")
	List<DocumentoEntity> findByIdAspirante(@Param("idAspirante") Integer idAspirante);

	@Query("SELECT d FROM DocumentoEntity d LEFT JOIN FETCH d.estadodocumento WHERE d.idAspirante = :idAspirante AND d.idDocumentosrequisitoconsejocohorte = :idDocReqConsejoCohorte")
	Optional<DocumentoEntity> findByIdAspiranteAndIdDocumentosrequisitoconsejocohorte(
		@Param("idAspirante") Integer idAspirante,
		@Param("idDocReqConsejoCohorte") Integer idDocumentosrequisitoconsejocohorte);

	@Query("SELECT d FROM DocumentoEntity d LEFT JOIN FETCH d.estadodocumento WHERE d.idAspirante = :idAspirante AND d.idDocumentosrequisitoprogramacohorte = :idDocReqProgramaCohorte")
	Optional<DocumentoEntity> findByIdAspiranteAndIdDocumentosrequisitoprogramacohorte(
		@Param("idAspirante") Integer idAspirante,
		@Param("idDocReqProgramaCohorte") Integer idDocumentosrequisitoprogramacohorte);

	@Modifying
	@Transactional
	@Query("UPDATE DocumentoEntity d SET d.idEstadodocumento = :idEstado, d.observaciones = :observaciones WHERE d.id = :idDocumento")
	int updateEstadoDocumentoById(
		@Param("idDocumento") Integer idDocumento,
		@Param("idEstado") Integer idEstado,
		@Param("observaciones") String observaciones);

	@Query("SELECT COUNT(d) FROM DocumentoEntity d WHERE d.idDocumentosrequisitoconsejocohorte = :idDocReqConsejoCohorte")
	int countByIdDocumentosrequisitoconsejocohorte(@Param("idDocReqConsejoCohorte") Integer idDocReqConsejoCohorte);

	@Query("SELECT COUNT(d) FROM DocumentoEntity d WHERE d.idDocumentosrequisitoprogramacohorte = :idDocReqProgramaCohorte")
	int countByIdDocumentosrequisitoprogramacohorte(@Param("idDocReqProgramaCohorte") Integer idDocReqProgramaCohorte);
}
