/*
 * Created on 2026-05-30 ( 22:06:13 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.PagorecibomatriculaEntity;
import java.util.List;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

/**
 * Spring Data JPA repository for the PagorecibomatriculaEntity entity.
 *
 * This interface extends {@link JpaRepository}, so it automatically inherits
 * standard persistence operations, including:
 * <ul>
 *   <li> Create/update entities: {@link JpaRepository#save(Object)} and {@link JpaRepository#saveAll(Iterable)}</li>
 *   <li> Basic queries: {@link JpaRepository#findById(Object)}, {@link JpaRepository#findAll()}, and {@link JpaRepository#getReferenceById(Object)}</li>
 *   <li> Validation and counting: {@link JpaRepository#existsById(Object)} and {@link JpaRepository#count()}</li>
 *   <li> Deletion: {@link JpaRepository#deleteById(Object)}, {@link JpaRepository#delete(Object)}, and {@link JpaRepository#deleteAll()}</li>
 *   <li> Paging and sorting: {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Pageable)}
 *     and {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Sort)}</li>
 * </ul>
 *
 * It can also be extended with derived query methods (findBy...),
 * following Spring Data JPA conventions.
 *
 * @category Repository
 * @version 1.0.0
 * @see JpaRepository
 * @see org.springframework.data.repository.CrudRepository
 * @see org.springframework.data.repository.PagingAndSortingRepository
 * @author a-cubica-r
 *
 */
@Repository
public interface PagorecibomatriculaRepository extends JpaRepository<PagorecibomatriculaEntity, Integer> {

	PagorecibomatriculaEntity findFirstByPago_IdAspiranteAndEstado_TipoIgnoreCaseAndEstado_EntidadIgnoreCaseOrderByIdDesc(
			Integer idAspirante, String tipoEstado, String entidadEstado);

	boolean existsByPago_IdAspiranteAndEstado_TipoIgnoreCaseAndEstado_EntidadIgnoreCase(Integer idAspirante,
			String tipoEstado, String entidadEstado);

	// Insert specific finders here 

	@Query("select r from PagorecibomatriculaEntity r "
		+ "join fetch r.pago p "
		+ "join fetch p.aspirante a "
		+ "left join fetch a.persona per "
		+ "left join fetch a.cohorte coh "
		+ "left join fetch coh.programa prog "
		+ "left join fetch r.estado est "
		+ "where prog.id = :programaId")
	List<PagorecibomatriculaEntity> findByProgramaIdWithJoins(@Param("programaId") Integer programaId);

		@Query("select new ufps.edu.co.rest.dto.PagoreciboDirectorProjectionDTO(r.id, p.id, a.id, concat(coalesce(per.nombres,''), ' ', coalesce(per.apellidos,'')), r.fechavencimiento, r.urlrecibo, r.urlfactura, r.referenciapago, r.valorpago, r.idEstado, est.tipo) "
			+ "from PagorecibomatriculaEntity r "
			+ "join r.pago p "
			+ "join p.aspirante a "
			+ "left join a.persona per "
			+ "left join a.cohorte coh "
			+ "left join coh.programa prog "
			+ "left join r.estado est "
			+ "where prog.id = :programaId")
		List<ufps.edu.co.rest.dto.PagoreciboDirectorProjectionDTO> findDirectorByProgramaId(@Param("programaId") Integer programaId);

		@Query(value = "select new ufps.edu.co.rest.dto.PagoreciboDirectorProjectionDTO(r.id, p.id, a.id, concat(coalesce(per.nombres,''), ' ', coalesce(per.apellidos,'')), r.fechavencimiento, r.urlrecibo, r.urlfactura, r.referenciapago, r.valorpago, r.idEstado, est.tipo) "
			+ "from PagorecibomatriculaEntity r "
			+ "join r.pago p "
			+ "join p.aspirante a "
			+ "left join a.persona per "
			+ "left join a.cohorte coh "
			+ "left join coh.programa prog "
			+ "left join r.estado est "
			+ "where prog.id = :programaId",
			countQuery = "select count(r) from PagorecibomatriculaEntity r join r.pago p join p.aspirante a left join a.cohorte coh left join coh.programa prog where prog.id = :programaId")
		org.springframework.data.domain.Page<ufps.edu.co.rest.dto.PagoreciboDirectorProjectionDTO> findDirectorByProgramaId(@Param("programaId") Integer programaId, org.springframework.data.domain.Pageable pageable);

	//List<PagorecibomatriculaEntity> findByXxx(String xxx);

	//List<PagorecibomatriculaEntity> findByXxxStartingWith(String xxx);

	//List<PagorecibomatriculaEntity> findByXxxContaining(String xxx);

	//List<PagorecibomatriculaEntity> findByYyy(BigDecimal yyy);

	//List<PagorecibomatriculaEntity> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);
}
