/*
 * Created on 2026-05-30 ( 22:06:13 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.PagoreciboinscripcionEntity;
import java.util.List;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

/**
 * Spring Data JPA repository for the PagoreciboinscripcionEntity entity.
 *
 * This interface extends {@link JpaRepository}, so it automatically inherits
 * standard persistence operations, including:
 * <ul>
 *   <li> Create/update entities: {@link JpaRepository#save(Object)} and {@link JpaRepository#saveAll(Iterable)}</li>
 *   <li> Basic queries: {@link JpaRepository#findById(Object)}, {@link JpaRepository#findAll()}, and {@link JpaRepository#getReferenceById(Object)}</li>
 *   <li> Validation and counting: {@link JpaRepository#existsById(Object)} and {@link JpaRepository#count()}</li>
 *   <li> Deletion: {@link JpaRepository#deleteById(Object)}, {@link JpaRepository#delete(Object)}, and {@link JpaRepository#deleteAll()}</li>
 *   <li> Paging and sorting: {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Pageable)}
 *     and {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Sort)}</li>
 * </ul>
 *
 * It can also be extended with derived query methods (findBy...),
 * following Spring Data JPA conventions.
 *
 * @category Repository
 * @version 1.0.0
 * @see JpaRepository
 * @see org.springframework.data.repository.CrudRepository
 * @see org.springframework.data.repository.PagingAndSortingRepository
 * @author a-cubica-r
 *
 */
@Repository
public interface PagoreciboinscripcionRepository extends JpaRepository<PagoreciboinscripcionEntity, Integer> {

	Optional<PagoreciboinscripcionEntity> findFirstByPago_IdAspiranteAndEstado_TipoIgnoreCaseAndEstado_EntidadIgnoreCaseOrderByIdDesc(
			Integer idAspirante, String tipo, String entidad);

	boolean existsByPago_IdAspiranteAndEstado_TipoIgnoreCaseAndEstado_EntidadIgnoreCase(Integer idAspirante,
			String tipo, String entidad);

	//List<PagoreciboinscripcionEntity> findByXxx(String xxx);

	@Query("select r from PagoreciboinscripcionEntity r "
		+ "join fetch r.pago p "
		+ "join fetch p.aspirante a "
		+ "left join fetch a.persona per "
		+ "left join fetch a.cohorte coh "
		+ "left join fetch coh.programa prog "
		+ "left join fetch r.estado est "
		+ "where prog.id = :programaId")
	List<PagoreciboinscripcionEntity> findByProgramaIdWithJoins(@Param("programaId") Integer programaId);

	//List<PagoreciboinscripcionEntity> findByXxxStartingWith(String xxx);

	//List<PagoreciboinscripcionEntity> findByXxxContaining(String xxx);

	//List<PagoreciboinscripcionEntity> findByYyy(BigDecimal yyy);

	//List<PagoreciboinscripcionEntity> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);
}
