/*
 * Created on 2026-05-18 ( 01:57:56 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.repositories;

import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ufps.edu.co.persistence.entities.UsuarioEntity;

/**
 * Spring Data JPA repository for the UsuarioEntity entity.
 *
 * This interface extends {@link JpaRepository}, so it automatically inherits
 * standard persistence operations, including:
 * <ul>
 *   <li> Create/update entities: {@link JpaRepository#save(Object)} and {@link JpaRepository#saveAll(Iterable)}</li>
 *   <li> Basic queries: {@link JpaRepository#findById(Object)}, {@link JpaRepository#findAll()}, and {@link JpaRepository#getReferenceById(Object)}</li>
 *   <li> Validation and counting: {@link JpaRepository#existsById(Object)} and {@link JpaRepository#count()}</li>
 *   <li> Deletion: {@link JpaRepository#deleteById(Object)}, {@link JpaRepository#delete(Object)}, and {@link JpaRepository#deleteAll()}</li>
 *   <li> Paging and sorting: {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Pageable)}
 *     and {@link org.springframework.data.repository.PagingAndSortingRepository#findAll(org.springframework.data.domain.Sort)}</li>
 * </ul>
 *
 * It can also be extended with derived query methods (findBy...),
 * following Spring Data JPA conventions.
 *
 * @category Repository
 * @version 1.0.0
 * @see JpaRepository
 * @see org.springframework.data.repository.CrudRepository
 * @see org.springframework.data.repository.PagingAndSortingRepository
 * @author a-cubica-r
 *
 */
@Repository
public interface UsuarioRepository extends JpaRepository<UsuarioEntity, Integer> {

	Optional<UsuarioEntity> findByNombreusuario(String nombreusuario);

	Optional<UsuarioEntity> findByIdPersona(Integer idPersona);

	@Query("SELECT u.idPersona FROM UsuarioEntity u WHERE u.nombreusuario = :nombreusuario")
	Optional<Integer> findIdPersonaByNombreusuario(@Param("nombreusuario") String nombreusuario);

	@Query("SELECT u.idPersona FROM UsuarioEntity u WHERE u.id = :id")
	Optional<Integer> findIdPersonaById(@Param("id") Integer id);

	// Insert specific finders here

	//List<UsuarioEntity> findByXxx(String xxx);

	//List<UsuarioEntity> findByXxxStartingWith(String xxx);

	//List<UsuarioEntity> findByXxxContaining(String xxx);

	//List<UsuarioEntity> findByYyy(BigDecimal yyy);

	//List<UsuarioEntity> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);
}
