/*
 * Created on 2026-05-24 ( 17:03:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.util.List;

/**
 * DTO class for "Documentopersona"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DocumentopersonaDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private String numerodocumento ;
    private Integer idTipodocumento ;
    private Integer idLugarexpedicion ;
    //--- LINKS ( RELATIONSHIPS )
    private TipodocumentopersonaDTO tipodocumentopersona ; 
    private UbicacionDTO ubicacion ; 
    private List<PersonaDTO> personaList ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Documentopersona[");
		sb.append("id=").append(id);
		sb.append(separator).append("numerodocumento=").append(numerodocumento);
		sb.append(separator).append("idTipodocumento=").append(idTipodocumento);
		sb.append(separator).append("idLugarexpedicion=").append(idLugarexpedicion);
		sb.append("]");
		return sb.toString();
	}
}
