/*
 * Created on 2026-05-30 ( 22:06:13 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * DTO class for "Pagoreciboinscripcion"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PagoreciboinscripcionDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private LocalDate fechavencimiento ;
    private String urlrecibo ;
    private String urlfactura ;
    private String referenciapago ;
    private BigDecimal valorpago ;
    private Integer idEstado ;
    private Integer idPago ;
    //--- LINKS ( RELATIONSHIPS )
    private PagoDTO pago ; 
    private EstadoDTO estado ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Pagoreciboinscripcion[");
		sb.append("id=").append(id);
		sb.append(separator).append("fechavencimiento=").append(fechavencimiento);
		// attribute 'urlrecibo' (type String) not usable in toString() 
		// attribute 'urlfactura' (type String) not usable in toString() 
		// attribute 'referenciapago' (type String) not usable in toString() 
		sb.append(separator).append("valorpago=").append(valorpago);
		sb.append(separator).append("idEstado=").append(idEstado);
		sb.append(separator).append("idPago=").append(idPago);
		sb.append("]");
		return sb.toString();
	}
}
