/*
 * Created on 2026-05-18 ( 01:57:54 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.dto;

import java.io.Serializable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.math.BigDecimal;
import java.util.List;

/**
 * DTO class for "Programa"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ProgramaDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Integer id ;
    //--- OTHER DATA FIELDS 
    private String codigo ;
    private String correo ;
    private Integer creditos ;
    private Integer duracion ;
    private Integer idFacultad ;
    private Integer idOtros ;
    private Integer idSede ;
    private Integer idTiporegistro ;
    private Integer idModalidad ;
    private String nivelformacion ;
    private String nombre ;
    private String periodicidad ;
    private String rcmineducacion ;
    private String registrosnies ;
    private String titulo ;
    private BigDecimal valormatricula ;
    private Boolean esPosgrado ;
    //--- LINKS ( RELATIONSHIPS )
    private List<CargoDTO> cargoList ; 
    private List<CohorteDTO> cohorteList ; 
    private FacultadDTO facultad ; 
    private OtrosvaloresDTO otrosvalores ; 
    private SedeDTO sede ; 
    private TiporegistroDTO tiporegistro ; 

    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Programa[");
		sb.append("id=").append(id);
		sb.append(separator).append("codigo=").append(codigo);
		sb.append(separator).append("correo=").append(correo);
		sb.append(separator).append("creditos=").append(creditos);
		sb.append(separator).append("duracion=").append(duracion);
		sb.append(separator).append("idFacultad=").append(idFacultad);
		sb.append(separator).append("idOtros=").append(idOtros);
		sb.append(separator).append("idSede=").append(idSede);
		sb.append(separator).append("idTiporegistro=").append(idTiporegistro);
		sb.append(separator).append("nivelformacion=").append(nivelformacion);
		sb.append(separator).append("nombre=").append(nombre);
		sb.append(separator).append("periodicidad=").append(periodicidad);
		// attribute 'rcmineducacion' (type String) not usable in toString() 
		sb.append(separator).append("registrosnies=").append(registrosnies);
		sb.append(separator).append("titulo=").append(titulo);
		sb.append(separator).append("valormatricula=").append(valormatricula);
		sb.append("]");
		return sb.toString();
	}
}
