/*
 * Created on 2026-05-25 ( 18:46:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "Cohorte"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "cohorte")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CohorteEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="nombre", length=100)
    private String     nombre ;

    @Column(name="cupos", nullable=false)
    private Integer        cupos ;

    @Column(name="id_estado", nullable=false)
    private Integer        idEstado ;

    @Column(name="id_semestre", nullable=false)
    private Integer        idSemestre ;

    @Column(name="id_modalidad", nullable=false)
    private Integer        idModalidad ;

    @Column(name="id_plazodocumentacion", nullable=false)
    private Integer        idPlazodocumentacion ;

    @Column(name="id_plazoinscripcion", nullable=false)
    private Integer        idPlazoinscripcion ;

    @Column(name="id_plazopago", nullable=false)
    private Integer        idPlazopago ;

    @Column(name="id_programa", nullable=false)
    private Integer        idPrograma ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="cohorte")
    private List<AdmitidoEntity> admitidoList ; 

    @OneToMany(mappedBy="cohorte")
    private List<AspiranteEntity> aspiranteList ; 

    @ManyToOne
    @JoinColumn(name="id_estado", referencedColumnName="id", insertable=false, updatable=false)
    private EstadoEntity     estado ; 

    @ManyToOne
    @JoinColumn(name="id_semestre", referencedColumnName="id", insertable=false, updatable=false)
    private SemestreEntity   semestre ; 

    @ManyToOne
    @JoinColumn(name="id_modalidad", referencedColumnName="id", insertable=false, updatable=false)
    private ModalidadEntity  modalidad ; 

    @ManyToOne
    @JoinColumn(name="id_plazodocumentacion", referencedColumnName="id", insertable=false, updatable=false)
    private PlazoEntity      plazo ; 

    @ManyToOne
    @JoinColumn(name="id_plazoinscripcion", referencedColumnName="id", insertable=false, updatable=false)
    private PlazoEntity      plazo2 ; 

    @ManyToOne
    @JoinColumn(name="id_plazopago", referencedColumnName="id", insertable=false, updatable=false)
    private PlazoEntity      plazo3 ; 

    @ManyToOne
    @JoinColumn(name="id_programa", referencedColumnName="id", insertable=false, updatable=false)
    private ProgramaEntity   programa ; 

    @OneToMany(mappedBy="cohorte")
    private List<CriteriocohorteEntity> criteriocohorteList ; 

    @OneToMany(mappedBy="cohorte")
    private List<DocumentosrequisitoconsejocohorteEntity> documentosrequisitoconsejocohorteList ;

    @OneToMany(mappedBy="cohorte")
    private List<DocumentosrequisitoprogramacohorteEntity> documentosrequisitoprogramacohorteList ; 

    @OneToMany(mappedBy="cohorte")
    private List<PruebaEntity> pruebaList ; 

}
