/*
 * Created on 2026-05-25 ( 18:46:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.math.BigDecimal;
import java.util.List;


/**
 * JPA entity class for "Criterioevaluacion"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "criterioevaluacion")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CriterioevaluacionEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="nombre", nullable=false, length=100)
    private String     nombre ;

    @Column(name="descripcion", length=65535)
    private String     descripcion ;

    @Column(name="peso", nullable=false)
    private BigDecimal peso ;

    @Column(name="activo")
    private Boolean    activo ;

    @Column(name="id_programa", nullable=false)
    private Integer        idPrograma ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="criterioevaluacion")
    private List<CriteriocohorteEntity> criteriocohorteList ; 

    @ManyToOne
    @JoinColumn(name="id_programa", referencedColumnName="id", insertable=false, updatable=false)
    private ProgramaEntity   programa ; 

}
