/*
 * Created on 2026-05-25 ( 18:46:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDate;
import java.util.List;


/**
 * JPA entity class for "Documento"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "documento")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DocumentoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="enlaceurl", nullable=false, length=65535)
    private String     enlaceurl ;

    @Column(name="fechacargue", nullable=false)
    private LocalDate  fechacargue ;

    @Column(name="keyfile", nullable=false, length=255)
    private String     keyfile ;

    @Column(name="observaciones", length=65535)
    private String     observaciones ;

    @Column(name="id_administrativo")
    private Integer    idAdministrativo ;

    @Column(name="id_aspirante", nullable=false)
    private Integer        idAspirante ;

    @Column(name="id_estadodocumento", nullable=false)
    private Integer        idEstadodocumento ;

    @Column(name="id_plazo", nullable=true)
    private Integer    idPlazo ;

    @Column(name="id_documentosrequisitoprogramacohorte")
    private Integer    idDocumentosrequisitoprogramacohorte ;

    @Column(name="id_documentosrequisitoconsejocohorte")
    private Integer    idDocumentosrequisitoconsejocohorte ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="documento")
    private List<CambiodocumentoEntity> cambiodocumentoList ; 

    @OneToMany(mappedBy="documento2")
    private List<CambiodocumentoEntity> cambiodocumentoList2 ; 

    @ManyToOne
    @JoinColumn(name="id_administrativo", referencedColumnName="id", insertable=false, updatable=false)
    private AdministrativoEntity administrativo ; 

    @ManyToOne
    @JoinColumn(name="id_aspirante", referencedColumnName="id", insertable=false, updatable=false)
    private AspiranteEntity  aspirante ; 

    @ManyToOne
    @JoinColumn(name="id_estadodocumento", referencedColumnName="id", insertable=false, updatable=false)
    private EstadodocumentoEntity estadodocumento ; 

    @ManyToOne
    @JoinColumn(name="id_plazo", referencedColumnName="id", insertable=false, updatable=false)
    private PlazoEntity      plazo ; 

    @ManyToOne
    @JoinColumn(name="id_documentosrequisitoconsejocohorte", referencedColumnName="id", insertable=false, updatable=false)
    private DocumentosrequisitoconsejocohorteEntity documentosrequisitoconsejocohorte ; 

    @ManyToOne
    @JoinColumn(name="id_documentosrequisitoprogramacohorte", referencedColumnName="id", insertable=false, updatable=false)
    private DocumentosrequisitoprogramacohorteEntity documentosrequisitoprogramacohorte ; 

}
