/*
 * Created on 2026-05-25 ( 18:46:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDate;
import java.time.LocalTime;


/**
 * JPA entity class for "Entrevista"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "entrevista")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class EntrevistaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="fecha", nullable=false)
    private LocalDate  fecha ;

    @Column(name="motivocambio", length=65535)
    private String     motivocambio ;

    @Column(name="id_aspirante", nullable=false)
    private Integer        idAspirante ;

    @Column(name="id_estado", nullable=false)
    private Integer        idEstado ;

    @Column(name="id_tipoentrevista", nullable=false)
    private Integer        idTipoentrevista ;

    @Column(name="id_ubicacion", nullable=false)
    private Integer        idUbicacion ;

    @Column(name="tiempo", nullable=false)
    private LocalTime  tiempo ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_aspirante", referencedColumnName="id", insertable=false, updatable=false)
    private AspiranteEntity  aspirante ; 

    @ManyToOne
    @JoinColumn(name="id_estado", referencedColumnName="id", insertable=false, updatable=false)
    private EstadoEntity     estado ; 

    @ManyToOne
    @JoinColumn(name="id_tipoentrevista", referencedColumnName="id", insertable=false, updatable=false)
    private TipoentrevistaEntity tipoentrevista ; 

    @ManyToOne
    @JoinColumn(name="id_ubicacion", referencedColumnName="id", insertable=false, updatable=false)
    private UbicacionEntity  ubicacion ; 

}
