/*
 * Created on 2026-05-25 ( 18:46:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "Otrosvalores"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "otrosvalores")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class OtrosvaloresEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="carnet", nullable=false)
    private Boolean    carnet ;

    @Column(name="estampilla", nullable=false)
    private Boolean    estampilla ;

    @Column(name="seguro", nullable=false)
    private Boolean    seguro ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="otrosvalores")
    private List<ProgramaEntity> programaList ; 

}
