/*
 * Created on 2026-05-25 ( 18:46:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * JPA entity class for "Pago"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "pago")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PagoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="id_aspirante", nullable=false)
    private Integer        idAspirante ;

    @Column(name="id_estado", nullable=false)
    private Integer        idEstado ;

    @Column(name="id_pagoconcepto", nullable=false)
    private Integer        idPagoconcepto ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_aspirante", referencedColumnName="id", insertable=false, updatable=false)
    private AspiranteEntity  aspirante ; 

    @ManyToOne
    @JoinColumn(name="id_estado", referencedColumnName="id", insertable=false, updatable=false)
    private EstadoEntity     estado ; 

    @ManyToOne
    @JoinColumn(name="id_pagoconcepto", referencedColumnName="id", insertable=false, updatable=false)
    private PagoconceptoEntity pagoconcepto ; 

}
