/*
 * Created on 2026-05-30 ( 22:06:46 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.math.BigDecimal;
import java.time.LocalDate;


/**
 * JPA entity class for "Pagoreciboinscripcion"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "pagoreciboinscripcion")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PagoreciboinscripcionEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="fechavencimiento")
    private LocalDate  fechavencimiento ;

    @Column(name="urlrecibo", length=65535)
    private String     urlrecibo ;

    @Column(name="urlfactura", length=65535)
    private String     urlfactura ;

    @Column(name="referenciapago", length=65535)
    private String     referenciapago ;

    @Column(name="valorpago")
    private BigDecimal valorpago ;

    @Column(name="id_estado", nullable=false)
    private Integer        idEstado ;

    @Column(name="id_pago", nullable=false)
    private Integer        idPago ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_pago", referencedColumnName="id", insertable=false, updatable=false)
    private PagoEntity       pago ; 

    @ManyToOne
    @JoinColumn(name="id_estado", referencedColumnName="id", insertable=false, updatable=false)
    private EstadoEntity     estado ; 

}
