/*
 * Created on 2026-05-25 ( 18:47:00 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;


/**
 * JPA entity class for "Sede"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "sede")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SedeEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="id_ubicacion", nullable=false)
    private Integer        idUbicacion ;

    @Column(name="nombre", nullable=false, length=100)
    private String     nombre ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="sede")
    private List<ProgramaEntity> programaList ; 

    @ManyToOne
    @JoinColumn(name="id_ubicacion", referencedColumnName="id", insertable=false, updatable=false)
    private UbicacionEntity  ubicacion ; 

}
