/*
 * Created on 2026-05-25 ( 18:47:00 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDate;
import java.util.List;


/**
 * JPA entity class for "Semestre"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "semestre")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SemestreEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="fecha_fin", nullable=false)
    private LocalDate  fechaFin ;

    @Column(name="fecha_inicio", nullable=false)
    private LocalDate  fechaInicio ;

    @Column(name="id_estado", nullable=false)
    private Integer        idEstado ;

    @Column(name="nombre", nullable=false, length=100)
    private String     nombre ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="semestre")
    private List<CohorteEntity> cohorteList ; 

    @ManyToOne
    @JoinColumn(name="id_estado", referencedColumnName="id", insertable=false, updatable=false)
    private EstadoEntity     estado ; 

}
