/*
 * Created on 2026-05-25 ( 18:47:01 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * JPA entity class for "Usuario"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "usuarios")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UsuarioEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="id_clave", nullable=false)
    private Integer        idClave ;

    @Column(name="id_persona", nullable=false)
    private Integer        idPersona ;

    @Column(name="id_rol", nullable=false)
    private Integer        idRol ;

    @Column(name="nombreusuario", nullable=false, length=50)
    private String     nombreusuario ;

    @Column(name="cedula", length=100)
    private String     cedula ;

    @Column(name="codigo", length=100)
    private String     codigo ;

    @Column(name="email", length=100)
    private String     email ;

    @Column(name="foto_url", length=100)
    private String     fotoUrl ;

    @Column(name="google_id", length=100)
    private String     googleId ;

    @Column(name="moodleld", length=100)
    private String     moodleld ;

    @Column(name="`nombreCompleto`", length=100)
    private String     nombrecompleto ;

    @Column(name="`primerApellido`", length=100)
    private String     primerapellido ;

    @Column(name="`primerNombre`", length=100)
    private String     primernombre ;

    @Column(name="`segundoApellido`", length=100)
    private String     segundoapellido ;

    @Column(name="`segundoNombre`", length=100)
    private String     segundonombre ;

    @Column(name="telefono", length=100)
    private String     telefono ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="id_clave", referencedColumnName="id", insertable=false, updatable=false)
    private ClaveEntity      clave ; 

    @ManyToOne
    @JoinColumn(name="id_persona", referencedColumnName="id", insertable=false, updatable=false)
    private PersonaEntity    persona ; 

    @ManyToOne
    @JoinColumn(name="id_rol", referencedColumnName="id", insertable=false, updatable=false)
    private RolEntity        rol ; 

}
