/*
 * Created on 2026-05-18 ( 01:57:56 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services.commons;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;
import org.modelmapper.ModelMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;

/**
 * Abstract class for REST services <br>
 *
 * @author Telosys
 *
 * @param <ENTITY>
 * @param <DTO>
 */
public abstract class GenericService<ENTITY, DTO> {

    @Autowired
    protected ModelMapper mapper;

    private final Class<ENTITY> entityClass;
    private final Class<DTO> dtoClass;

    protected GenericService(Class<ENTITY> entityClass, Class<DTO> dtoClass) {
        this.entityClass  = entityClass;
        this.dtoClass = dtoClass;
    }

    /**
     * Converts DTO to JPA ENTITY
     */
    protected ENTITY dtoToEntity(DTO dto) {
        return mapper.map(dto, entityClass);
    }

    /**
     * Converts JPA ENTITY to DTO
     */
    @Transactional(readOnly = true)
    protected DTO entityToDto(ENTITY entity) {
        if (entity == null) {
            return null;
        }
        return mapper.map(entity, dtoClass);
    }

    /**
     * Converts an Optional JPA ENTITY to DTO
     */
    @Transactional(readOnly = true)
    protected DTO entityToDto(Optional<ENTITY> optionalEntity) {
        return optionalEntity.map(this::entityToDto).orElse(null);
    }

    /**
     * Converts a collection of JPA ENTITIES to a list of DTO
     */
    @Transactional(readOnly = true)
    protected List<DTO> entityListToDtoList(Iterable<ENTITY> entities) {
        return StreamSupport.stream(entities.spliterator(), false)
                .map(this::entityToDto)
                .collect(Collectors.toList());
    }
}