/*
 * Created on 2026-05-18 ( 01:57:56 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services.commons;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.mapping.EntityMapper;

/**
 * Abstract class for REST services <br>
 *
 * @author Telosys
 *
 * @param <ENTITY>
 * @param <DTO>
 */
public abstract class GenericService<ENTITY, DTO> {

    /**
     * MapStruct mapper for this ENTITY/DTO pair, resolved by Spring from the generic types of the subclass
     */
    @Autowired
    protected EntityMapper<ENTITY, DTO> mapper;

    protected GenericService(Class<ENTITY> entityClass, Class<DTO> dtoClass) {
        // Types are resolved through the injected EntityMapper; the parameters are kept so subclasses stay unchanged
    }

    /**
     * Converts DTO to JPA ENTITY
     */
    protected ENTITY dtoToEntity(DTO dto) {
        if (dto == null) {
            throw new IllegalArgumentException("source cannot be null");
        }
        return mapper.toEntity(dto);
    }

    /**
     * Converts JPA ENTITY to DTO
     */
    @Transactional(readOnly = true)
    protected DTO entityToDto(ENTITY entity) {
        if (entity == null) {
            return null;
        }
        return mapper.toDto(entity);
    }

    /**
     * Converts an Optional JPA ENTITY to DTO
     */
    @Transactional(readOnly = true)
    protected DTO entityToDto(Optional<ENTITY> optionalEntity) {
        return optionalEntity.map(this::entityToDto).orElse(null);
    }

    /**
     * Converts a collection of JPA ENTITIES to a list of DTO
     */
    @Transactional(readOnly = true)
    protected List<DTO> entityListToDtoList(Iterable<ENTITY> entities) {
        return StreamSupport.stream(entities.spliterator(), false)
                .map(this::entityToDto)
                .collect(Collectors.toList());
    }
}