/*
 * Created on 2026-05-24 ( 14:49:14 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.controllers.rest;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import ufps.edu.co.services.core.crud.CriteriocohorteCoreService;
import ufps.edu.co.records.input.entity.CriteriocohorteInput.CRITERIOCOHORTE_CREATE;
import ufps.edu.co.records.input.entity.CriteriocohorteInput.CRITERIOCOHORTE_DELETE;
import ufps.edu.co.records.input.entity.CriteriocohorteInput.CRITERIOCOHORTE_FIND;
import ufps.edu.co.records.input.entity.CriteriocohorteInput.CRITERIOCOHORTE_UPDATE;
import ufps.edu.co.records.output.entity.CriteriocohorteOutput;

@RestController
@RequestMapping(value = "/api/v1/criteriocohorte", produces = MediaType.APPLICATION_JSON_VALUE)
public class CriteriocohorteRestController {

    @Autowired
    private CriteriocohorteCoreService processor;

    /**
     * Get ALL
     *
     * @return 200 con lista de DTO
     */
    @GetMapping("")
    public ResponseEntity<List<CriteriocohorteOutput>> findAll() {
        List<CriteriocohorteOutput> list = processor.findAll();
        return ResponseEntity.ok(list); // 200 OK
    }

    /**
     * Get ONE identified by the given PK
     *
     * @param id
     * @return 200 con DTO o 404 si no existe
     */
    @GetMapping("/{id}")
    public ResponseEntity<CriteriocohorteOutput> findById(@PathVariable Integer id) {
        try {
            CriteriocohorteOutput criteriocohorteOutput = processor.findById(new CRITERIOCOHORTE_FIND(id));
            if ( criteriocohorteOutput != null ) {
                return ResponseEntity.ok(criteriocohorteOutput); // 200 OK
            } else {
                return ResponseEntity.notFound().build(); // 404 Not found
            }
        } catch (RuntimeException e) {
            return ResponseEntity.notFound().build(); // 404 Not found
        }
    }

    /**
     * Create
     *
     * @param criteriocohorteDTO
     * @return 201 creado o 409 si ya existe
     */
    @PostMapping("")
    public ResponseEntity<CriteriocohorteOutput> create(@RequestBody CRITERIOCOHORTE_CREATE request) {
        CriteriocohorteOutput created = processor.create(request);
        return ResponseEntity.status(HttpStatus.CREATED).body(created); // 201 Created
    }

    /**
     * Update if exists
     *
     * @param id
     * @param criteriocohorteDTO
     * @return 200 con DTO actualizado o 404 si no existe
     */
    @PutMapping("/{id}")
    public ResponseEntity<CriteriocohorteOutput> update(@PathVariable Integer id, @RequestBody CRITERIOCOHORTE_UPDATE request) {
        try {
            CRITERIOCOHORTE_UPDATE input = new CRITERIOCOHORTE_UPDATE(id, request.idCohorte(), request.idCriterio(), request.pesoSnapshot());
            CriteriocohorteOutput updated = processor.update(input);
            return ResponseEntity.ok(updated); // 200 OK
        } catch (RuntimeException e) {
            return ResponseEntity.notFound().build(); // 404 Not found
        }
    }

    /**
     * Delete by PK
     *
     * @param id
     * @return 204 eliminado o 404 si no existe
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteById(@PathVariable Integer id) {
        try {
            processor.deleteById(new CRITERIOCOHORTE_DELETE(id));
            return ResponseEntity.noContent().build(); // 204 No content
        } catch (RuntimeException e) {
            return ResponseEntity.notFound().build(); // 404 Not found
        }
    }
}