/*
 * Created on 2026-05-18 ( 01:57:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.AdministrativoEntity;
import ufps.edu.co.persistence.repositories.AdministrativoRepository;
import ufps.edu.co.rest.dto.AdministrativoDTO;
import ufps.edu.co.rest.dto.CargoDTO;
import ufps.edu.co.rest.dto.DocumentoDTO;
import ufps.edu.co.rest.dto.EstadoDTO;
import ufps.edu.co.rest.dto.PersonaDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Administrativo" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class AdministrativoService extends GenericService<AdministrativoEntity, AdministrativoDTO> {

    @Autowired
    private AdministrativoRepository repository;

    @Autowired
    private EstadoService estadoService;

    public AdministrativoService() {
        super(AdministrativoEntity.class, AdministrativoDTO.class);
    }

    @Override
    protected AdministrativoDTO entityToDto(AdministrativoEntity e) {
        if (e == null) return null;

        CargoDTO cargoDto = e.getCargo() != null ? CargoDTO.builder()
                .id(e.getCargo().getId())
                .nombre(e.getCargo().getNombre())
                .descripcion(e.getCargo().getDescripcion())
                .idFacultad(e.getCargo().getIdFacultad())
                .idPrograma(e.getCargo().getIdPrograma())
                .build() : null;

        EstadoDTO estadoDto = e.getEstado() != null ? EstadoDTO.builder()
                .id(e.getEstado().getId())
                .entidad(e.getEstado().getEntidad())
                .tipo(e.getEstado().getTipo())
                .build() : null;

        PersonaDTO personaDto = e.getPersona() != null ? PersonaDTO.builder()
                .id(e.getPersona().getId())
                .nombres(e.getPersona().getNombres())
                .apellidos(e.getPersona().getApellidos())
                .correo(e.getPersona().getCorreo())
                .celular(e.getPersona().getCelular())
                .telefono(e.getPersona().getTelefono())
                .fechanacimiento(e.getPersona().getFechanacimiento())
                .egresadoufps(e.getPersona().getEgresadoufps())
                .empresa(e.getPersona().getEmpresa())
                .experiencialaboral(e.getPersona().getExperiencialaboral())
                .promediopregrado(e.getPersona().getPromediopregrado())
                .titulopregrado(e.getPersona().getTitulopregrado())
                .titulosposgrados(e.getPersona().getTitulosposgrados())
                .idDocumentopersona(e.getPersona().getIdDocumentopersona())
                .idCapacidadexepcional(e.getPersona().getIdCapacidadexepcional())
                .idDiscapacidad(e.getPersona().getIdDiscapacidad())
                .idEstadocivil(e.getPersona().getIdEstadocivil())
                .idGenero(e.getPersona().getIdGenero())
                .idGrupoetnico(e.getPersona().getIdGrupoetnico())
                .idPoblacionindigena(e.getPersona().getIdPoblacionindigena())
                .idUbicacionnacimiento(e.getPersona().getIdUbicacionnacimiento())
                .idUbicaciontrabajo(e.getPersona().getIdUbicaciontrabajo())
                .idUbicacionvivienda(e.getPersona().getIdUbicacionvivienda())
                .build() : null;

        List<DocumentoDTO> documentoListDto = e.getDocumentoList() != null
                ? e.getDocumentoList().stream().map(d -> DocumentoDTO.builder()
                        .id(d.getId())
                        .enlaceurl(d.getEnlaceurl())
                        .fechacargue(d.getFechacargue())
                        .keyfile(d.getKeyfile())
                        .observaciones(d.getObservaciones())
                        .idAdministrativo(d.getIdAdministrativo())
                        .idAspirante(d.getIdAspirante())
                        .idEstadodocumento(d.getIdEstadodocumento())
                        .idPlazo(d.getIdPlazo())
                        .idDocumentosrequisitoconsejocohorte(d.getIdDocumentosrequisitoconsejocohorte())
                        .idDocumentosrequisitoprogramacohorte(d.getIdDocumentosrequisitoprogramacohorte())
                        .build())
                        .toList() : null;

        return AdministrativoDTO.builder()
                .id(e.getId())
                .fechainicio(e.getFechainicio())
                .fechasalida(e.getFechasalida())
                .idCargo(e.getIdCargo())
                .idEstado(e.getIdEstado())
                .idPersona(e.getIdPersona())
                .cargo(cargoDto)
                .estado(estadoDto)
                .persona(personaDto)
                .documentoList(documentoListDto)
                .build();
    }

    @Transactional(readOnly = true)
    public List<AdministrativoDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public AdministrativoDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    @Transactional(readOnly = true)
    public AdministrativoDTO findByIdPersona(Integer idPersona) {
        return entityToDto(repository.findByIdPersona(idPersona));
    }

    @Transactional(readOnly = true)
    public Integer findIdByIdPersona(Integer idPersona) {
        return repository.findIdByIdPersona(idPersona).orElse(null);
    }

    @Transactional(readOnly = true)
    public Integer findIdProgramaByIdPersona(Integer idPersona) {
        return repository.findIdProgramaByIdPersona(idPersona).orElse(null);
    }

    @Transactional(readOnly = true)
    public String findCargoNombreByIdPersona(Integer idPersona) {
        return repository.findCargoNombreByIdPersona(idPersona).orElse(null);
    }

    public AdministrativoDTO create(AdministrativoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public AdministrativoDTO update(Integer id, AdministrativoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Administrativo no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Administrativo no encontrado con id: " + id));
        repository.deleteById(id);
    }

    public AdministrativoDTO createDirectorPrograma(Integer idPersona, Integer idCargo) {
        EstadoDTO estadoActivo = requireEstado("ACTIVO", "administrativo");
        EstadoDTO estadoInactivo = requireEstado("INACTIVO", "administrativo");
        LocalDate fechaActual = LocalDate.now();

        deactivateExistingAdministrativos(idPersona, idCargo, estadoInactivo.getId(), fechaActual);

        AdministrativoDTO nuevo = AdministrativoDTO.builder()
                .fechainicio(fechaActual)
                .fechasalida(null)
                .idCargo(idCargo)
                .idEstado(estadoActivo.getId())
                .idPersona(idPersona)
                .build();

        return create(nuevo);
    }

    private void deactivateExistingAdministrativos(Integer idPersona, Integer idCargo, Integer idEstadoInactivo,
            LocalDate fechaActual) {
        List<AdministrativoEntity> administratives = repository.findAllByIdCargo(idCargo);
        administratives.addAll(repository.findAllByIdPersona(idPersona));

        administratives.stream()
                .filter(administrativo -> administrativo != null && administrativo.getId() != null)
                .map(AdministrativoEntity::getId)
                .distinct()
                .forEach(id -> repository.findById(id).ifPresent(administrativo -> {
                    administrativo.setIdEstado(idEstadoInactivo);
                    administrativo.setFechasalida(fechaActual);
                    repository.save(administrativo);
                }));
    }

    private EstadoDTO requireEstado(String tipo, String entidad) {
        EstadoDTO estado = estadoService.findByTipoAndEntidad(tipo, entidad);
        return Optional.ofNullable(estado)
                .orElseThrow(() -> new RuntimeException("Estado no encontrado: " + tipo + " / " + entidad));
    }

    @Transactional(readOnly = true)
    public AdministrativoDTO findDirectorByIdPrograma(Integer idPrograma) {
        return repository.findDirectorByIdPrograma(idPrograma)
                .map(e -> entityToDto(java.util.Optional.of(e)))
                .orElse(null);
    }

    public List<AdministrativoDTO> findPosiblesDirectores() {

        List<String> nombres = List.of("DIRECTOR DE FACULTAD", "DIRECTOR DE PROGRAMA", "ADMINISTADOR", "SUPER ADMINISTRADOR");

        List<AdministrativoEntity> entities = repository.findByCargoNombreNotIn(nombres);

        return entityListToDtoList(entities);
    }
}