/*
 * Created on 2026-05-18 ( 01:57:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.AspiranteEntity;
import ufps.edu.co.persistence.entities.DocumentopersonaEntity;
import ufps.edu.co.persistence.entities.PersonaEntity;
import ufps.edu.co.persistence.repositories.AspiranteRepository;
import ufps.edu.co.rest.dto.AspiranteDTO;
import ufps.edu.co.rest.dto.AspiranteCheckoutDTO;
import ufps.edu.co.rest.dto.PagoCheckoutPreviewDataDTO;
import ufps.edu.co.rest.dto.DocumentopersonaDTO;
import ufps.edu.co.rest.dto.EstadoDTO;
import ufps.edu.co.rest.dto.PersonaDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Aspirante" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class AspiranteService extends GenericService<AspiranteEntity, AspiranteDTO> {

    @Autowired
    private AspiranteRepository repository;

    public AspiranteService() {
        super(AspiranteEntity.class, AspiranteDTO.class);
    }

    @Override
    protected AspiranteDTO entityToDto(AspiranteEntity e) {
        EstadoDTO estadoDto = e.getEstado() != null ? EstadoDTO.builder()
                .id(e.getEstado().getId())
                .entidad(e.getEstado().getEntidad())
                .tipo(e.getEstado().getTipo())
                .build() : null;

        PersonaDTO personaDto = null;
        PersonaEntity pe = e.getPersona();
        if (pe != null) {
            DocumentopersonaEntity dp = pe.getDocumentopersona();
            DocumentopersonaDTO dpDto = dp != null ? DocumentopersonaDTO.builder()
                    .id(dp.getId())
                    .numerodocumento(dp.getNumerodocumento())
                    .build() : null;
            personaDto = PersonaDTO.builder()
                    .id(pe.getId())
                    .nombres(pe.getNombres())
                    .apellidos(pe.getApellidos())
                    .correo(pe.getCorreo())
                    .documentopersona(dpDto)
                    .build();
        }

        return AspiranteDTO.builder()
                .id(e.getId())
                .puntuacion(e.getPuntuacion())
                .idCohorte(e.getIdCohorte())
                .idEstado(e.getIdEstado())
                .idPersona(e.getIdPersona())
                .idTipovinculacion(e.getIdTipovinculacion())
                .estado(estadoDto)
                .persona(personaDto)
                .build();
    }

    @Transactional(readOnly = true)
    public List<AspiranteDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public AspiranteDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    @Transactional(readOnly = true)
    public AspiranteCheckoutDTO findCheckoutById(Integer idAspirante) {
        return repository.findCheckoutById(idAspirante)
                .orElse(null);
    }

    @Transactional(readOnly = true)
    public PagoCheckoutPreviewDataDTO findCheckoutPreviewById(Integer idAspirante) {
        return repository.findCheckoutPreviewById(idAspirante)
                .orElse(null);
    }

    public AspiranteDTO create(AspiranteDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public AspiranteDTO update(Integer id, AspiranteDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Aspirante no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Aspirante no encontrado con id: " + id));
        repository.deleteById(id);
    }

    @Transactional(readOnly = true)
    public List<AspiranteDTO> findWithDocuments() {
        return entityListToDtoList(repository.findValidados());
    }

    @Transactional(readOnly = true)
    public List<AspiranteDTO> findCalificados() {
        return entityListToDtoList(repository.findCalificados());
    }

    @Transactional(readOnly = true)
    public List<AspiranteDTO> findPorCalificar() {
        return entityListToDtoList(repository.findPorCalificar());
    }

    @Transactional(readOnly = true)
    public List<AspiranteDTO> findByCohorte(int idCohorte) {
        return entityListToDtoList(repository.findByIdCohorte(idCohorte));
    }

    @Transactional(readOnly = true)
    public List<AspiranteDTO> findValidadosByCohorte(int cohorteId) {
        List<String> tipos = List.of("VALIDADO_POR_CALIFICAR", "VALIDADO_EN_PROGRESO", "VALIDADO_CALIFICADO");
        return entityListToDtoList(repository.findByIdCohorteAndEstadoTipoIn(cohorteId, tipos));
    }

    @Transactional(readOnly = true)
    public List<AspiranteDTO> findAdmitidosByCohorte(int cohorteId) {
        return entityListToDtoList(repository.findByIdCohorteAndEstadoTipoIn(cohorteId, List.of("ADMITIDO")));
    }

    public long countValidados() {
        return repository.countByEstadoTipoIn(
                List.of("VALIDADO_POR_CALIFICAR", "VALIDADO_EN_PROGRESO", "VALIDADO_CALIFICADO"));
    }

    public long countPorCalificar() {
        return repository.countByEstadoTipoIn(
                List.of("VALIDADO_POR_CALIFICAR", "VALIDADO_EN_PROGRESO"));
    }

    public long countCalificados() {
        return repository.countByEstadoTipoIn(List.of("VALIDADO_CALIFICADO"));
    }

    public long countByCohorte(Integer cohorteId) {
        return repository.countByIdCohorte(cohorteId);
    }

    public long countValidadosByCohorte(Integer cohorteId) {
        return repository.countByIdCohorteAndEstadoTipoIn(cohorteId,
                List.of("VALIDADO_POR_CALIFICAR", "VALIDADO_EN_PROGRESO"));
    }

    public long countCalificadosByCohorte(Integer cohorteId) {
        return repository.countByIdCohorteAndEstadoTipoIn(cohorteId, List.of("VALIDADO_CALIFICADO"));
    }

    public long countPorCalificarByCohorte(Integer cohorteId) {
        return repository.countByIdCohorteAndEstadoTipoIn(cohorteId,
                List.of("VALIDADO_POR_CALIFICAR", "VALIDADO_EN_PROGRESO"));
    }

    public long countPazYSalvoByCohorte(Integer cohorteId) {
        return repository.countByIdCohorteAndEstadoTipoIn(cohorteId, List.of("PAZ Y SALVO"));
    }

    public long countAdmitidosByCohorte(Integer cohorteId) {
        return repository.countByIdCohorteAndEstadoTipoIn(cohorteId, List.of("POR LEGALIZAR"));
    }

    @Transactional(readOnly = true)
    public AspiranteDTO findByIdPersona(Integer idPersona) {
        return entityToDto(repository.findFirstByIdPersona(idPersona));
    }

    @Transactional(readOnly = true)
    public Integer findIdPersonaById(Integer idAspirante) {
        return repository.findIdPersonaById(idAspirante).orElse(null);
    }

    @Transactional(readOnly = true)
    public Integer findIdByIdPersona(Integer idPersona) {
        return repository.findIdByIdPersona(idPersona).orElse(null);
    }

    @Transactional(readOnly = true)
    public String findEstadoTipoById(Integer id) {
        return repository.findEstadoTipoById(id).orElse(null);
    }

    @Transactional(readOnly = true)
    public Integer findIdCohorteById(Integer id) {
        return repository.findIdCohorteById(id).orElse(null);
    }

    @Transactional(readOnly = true)
    public java.math.BigDecimal findPuntuacionById(Integer id) {
        return repository.findPuntuacionById(id).orElse(null);
    }

    public AspiranteDTO updateEstado(Integer idAspirante, Integer idEstado) {
        AspiranteEntity entity = repository.findById(idAspirante)
                .orElseThrow(() -> new RuntimeException("Aspirante no encontrado con id: " + idAspirante));
        entity.setIdEstado(idEstado);
        repository.save(entity);
        return entityToDto(repository.findById(idAspirante).orElseThrow());
    }
}