/*
 * Created on 2026-05-18 ( 01:57:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.DepartamentoEntity;
import ufps.edu.co.persistence.repositories.DepartamentoRepository;
import ufps.edu.co.rest.dto.DepartamentoDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Departamento" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class DepartamentoService extends GenericService<DepartamentoEntity, DepartamentoDTO> {

    @Autowired
    private DepartamentoRepository repository;

    public DepartamentoService() {
        super(DepartamentoEntity.class, DepartamentoDTO.class);
    }

    @Transactional(readOnly = true)
    public List<DepartamentoDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public DepartamentoDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public DepartamentoDTO create(DepartamentoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public DepartamentoDTO update(Integer id, DepartamentoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Departamento no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    @Transactional(readOnly = true)
    public List<DepartamentoDTO> findByIdPais(Integer idPais) {
        // Build shallow DTOs to avoid ModelMapper cycles (pais -> departamento -> pais ...)
        return repository.findByIdPais(idPais).stream().map(entity -> {
            DepartamentoDTO dto = new DepartamentoDTO();
            dto.setId(entity.getId());
            dto.setIdPais(entity.getIdPais());
            dto.setNombre(entity.getNombre());
            return dto;
        }).toList();
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Departamento no encontrado con id: " + id));
        repository.deleteById(id);
    }
}