/*
 * Created on 2026-05-24 ( 17:03:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.DocumentosrequisitoconsejocohorteEntity;
import ufps.edu.co.persistence.repositories.DocumentosrequisitoconsejocohorteRepository;
import ufps.edu.co.rest.dto.DocumentosrequisitoconsejocohorteDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Documentosrequisitoconsejocohorte" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class DocumentosrequisitoconsejocohorteService extends GenericService<DocumentosrequisitoconsejocohorteEntity, DocumentosrequisitoconsejocohorteDTO> {

    @Autowired
    private DocumentosrequisitoconsejocohorteRepository repository;

    public DocumentosrequisitoconsejocohorteService() {
        super(DocumentosrequisitoconsejocohorteEntity.class, DocumentosrequisitoconsejocohorteDTO.class);
    }

    @Override
    protected DocumentosrequisitoconsejocohorteDTO entityToDto(DocumentosrequisitoconsejocohorteEntity e) {
        return DocumentosrequisitoconsejocohorteDTO.builder()
                .id(e.getId())
                .idDocrequisito(e.getIdDocrequisito())
                .idCohorte(e.getIdCohorte())
                .build();
    }

    @Transactional(readOnly = true)
    public List<DocumentosrequisitoconsejocohorteDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public DocumentosrequisitoconsejocohorteDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    @Transactional(readOnly = true)
    public List<DocumentosrequisitoconsejocohorteDTO> findByIdCohorte(Integer idCohorte) {
        return entityListToDtoList(repository.findByIdCohorte(idCohorte));
    }

    @Transactional(readOnly = true)
    public Map<Integer, String> findNombreMapByCohorte(Integer idCohorte) {
        return repository.findByIdCohorteWithRequisito(idCohorte).stream()
                .filter(dcc -> dcc.getDocumentosrequisitoconsejo() != null)
                .collect(Collectors.toMap(
                        DocumentosrequisitoconsejocohorteEntity::getId,
                        dcc -> dcc.getDocumentosrequisitoconsejo().getNombre()));
    }

    public DocumentosrequisitoconsejocohorteDTO create(DocumentosrequisitoconsejocohorteDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public DocumentosrequisitoconsejocohorteDTO update(Integer id, DocumentosrequisitoconsejocohorteDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documentosrequisitoconsejocohorte no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documentosrequisitoconsejocohorte no encontrado con id: " + id));
        repository.deleteById(id);
    }
}
