/*
 * Created on 2026-05-24 ( 17:03:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.DocumentosrequisitoprogramacohorteEntity;
import ufps.edu.co.persistence.repositories.DocumentosrequisitoprogramacohorteRepository;
import ufps.edu.co.rest.dto.DocumentosrequisitoprogramacohorteDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Documentosrequisitoprogramacohorte" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class DocumentosrequisitoprogramacohorteService extends GenericService<DocumentosrequisitoprogramacohorteEntity, DocumentosrequisitoprogramacohorteDTO> {

    @Autowired
    private DocumentosrequisitoprogramacohorteRepository repository;

    public DocumentosrequisitoprogramacohorteService() {
        super(DocumentosrequisitoprogramacohorteEntity.class, DocumentosrequisitoprogramacohorteDTO.class);
    }

    @Override
    protected DocumentosrequisitoprogramacohorteDTO entityToDto(DocumentosrequisitoprogramacohorteEntity e) {
        return DocumentosrequisitoprogramacohorteDTO.builder()
                .id(e.getId())
                .idDocrequisito(e.getIdDocrequisito())
                .idCohorte(e.getIdCohorte())
                .build();
    }

    @Transactional(readOnly = true)
    public List<DocumentosrequisitoprogramacohorteDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public DocumentosrequisitoprogramacohorteDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    @Transactional(readOnly = true)
    public List<DocumentosrequisitoprogramacohorteDTO> findByIdCohorte(Integer idCohorte) {
        return entityListToDtoList(repository.findByIdCohorte(idCohorte));
    }

    @Transactional(readOnly = true)
    public Map<Integer, String> findNombreMapByCohorte(Integer idCohorte) {
        return repository.findByIdCohorteWithRequisito(idCohorte).stream()
                .filter(dpc -> dpc.getDocumentosrequisitoprograma() != null)
                .collect(Collectors.toMap(
                        DocumentosrequisitoprogramacohorteEntity::getId,
                        dpc -> dpc.getDocumentosrequisitoprograma().getNombre()));
    }

    public DocumentosrequisitoprogramacohorteDTO create(DocumentosrequisitoprogramacohorteDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public DocumentosrequisitoprogramacohorteDTO update(Integer id, DocumentosrequisitoprogramacohorteDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documentosrequisitoprogramacohorte no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documentosrequisitoprogramacohorte no encontrado con id: " + id));
        repository.deleteById(id);
    }
}
