/*
 * Created on 2026-05-24 ( 17:03:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.DocumentosrequisitoprogramaEntity;
import ufps.edu.co.persistence.repositories.DocumentosrequisitoprogramaRepository;
import ufps.edu.co.rest.dto.DocumentosrequisitoprogramaDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Documentosrequisitoprograma" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class DocumentosrequisitoprogramaService extends GenericService<DocumentosrequisitoprogramaEntity, DocumentosrequisitoprogramaDTO> {

    @Autowired
    private DocumentosrequisitoprogramaRepository repository;

    public DocumentosrequisitoprogramaService() {
        super(DocumentosrequisitoprogramaEntity.class, DocumentosrequisitoprogramaDTO.class);
    }

    @Override
    protected DocumentosrequisitoprogramaDTO entityToDto(DocumentosrequisitoprogramaEntity e) {
        return DocumentosrequisitoprogramaDTO.builder()
                .id(e.getId())
                .nombre(e.getNombre())
                .tamanomaximo(e.getTamanomaximo())
                .urlformato(e.getUrlformato())
                .id_programa(e.getIdPrograma())
                .build();
    }

    @Override
    protected DocumentosrequisitoprogramaEntity dtoToEntity(DocumentosrequisitoprogramaDTO dto) {
        return DocumentosrequisitoprogramaEntity.builder()
                .id(dto.getId())
                .nombre(dto.getNombre())
                .tamanomaximo(dto.getTamanomaximo())
                .urlformato(dto.getUrlformato())
                .idPrograma(dto.getId_programa())
                .build();
    }

    @Transactional(readOnly = true)
    public List<DocumentosrequisitoprogramaDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public DocumentosrequisitoprogramaDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    @Transactional(readOnly = true)
    public List<DocumentosrequisitoprogramaDTO> findByIdPrograma(Integer idPrograma) {
        return entityListToDtoList(repository.findByIdPrograma(idPrograma));
    }

    @Transactional(readOnly = true)
    public List<DocumentosrequisitoprogramaDTO> findAllByIds(List<Integer> ids) {
        if (ids == null || ids.isEmpty()) return List.of();
        return entityListToDtoList(repository.findAllById(ids));
    }

    public DocumentosrequisitoprogramaDTO create(DocumentosrequisitoprogramaDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public DocumentosrequisitoprogramaDTO update(Integer id, DocumentosrequisitoprogramaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documentosrequisitoprograma no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documentosrequisitoprograma no encontrado con id: " + id));
        repository.deleteById(id);
    }
}
