/*
 * Created on 2026-05-24 ( 17:03:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.DocumentosrequisitoconsejoEntity;
import ufps.edu.co.persistence.repositories.DocumentosrequisitoconsejoRepository;
import ufps.edu.co.rest.dto.DocumentosrequisitoconsejoDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Documentosrequisitoconsejo" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class DocumentosrequisitoconsejoService extends GenericService<DocumentosrequisitoconsejoEntity, DocumentosrequisitoconsejoDTO> {

    @Autowired
    private DocumentosrequisitoconsejoRepository repository;

    public DocumentosrequisitoconsejoService() {
        super(DocumentosrequisitoconsejoEntity.class, DocumentosrequisitoconsejoDTO.class);
    }

    @Override
    protected DocumentosrequisitoconsejoDTO entityToDto(DocumentosrequisitoconsejoEntity e) {
        return DocumentosrequisitoconsejoDTO.builder()
                .id(e.getId())
                .nombre(e.getNombre())
                .tamanomaximo(e.getTamanomaximo())
                .urlformato(e.getUrlformato())
                .build();
    }

    @Transactional(readOnly = true)
    public List<DocumentosrequisitoconsejoDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public DocumentosrequisitoconsejoDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    @Transactional(readOnly = true)
    public List<DocumentosrequisitoconsejoDTO> findByIdPrograma(Integer idPrograma) {
        return entityListToDtoList(repository.findByIdPrograma(idPrograma));
    }

    @Transactional(readOnly = true)
    public List<DocumentosrequisitoconsejoDTO> findAllByIds(List<Integer> ids) {
        if (ids == null || ids.isEmpty()) return List.of();
        return entityListToDtoList(repository.findAllById(ids));
    }

    public DocumentosrequisitoconsejoDTO create(DocumentosrequisitoconsejoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public DocumentosrequisitoconsejoDTO update(Integer id, DocumentosrequisitoconsejoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documentosrequisitoconsejo no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documentosrequisitoconsejo no encontrado con id: " + id));
        repository.deleteById(id);
    }
}
