/*
 * Created on 2026-05-30 ( 22:06:13 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.PagoreciboinscripcionEntity;
import ufps.edu.co.persistence.repositories.PagoreciboinscripcionRepository;
import ufps.edu.co.rest.dto.PagoreciboinscripcionDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Pagoreciboinscripcion" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class PagoreciboinscripcionService
        extends GenericService<PagoreciboinscripcionEntity, PagoreciboinscripcionDTO> {

    @Autowired
    private PagoreciboinscripcionRepository repository;

    public PagoreciboinscripcionService() {
        super(PagoreciboinscripcionEntity.class, PagoreciboinscripcionDTO.class);
    }

    @Transactional(readOnly = true)
    public List<PagoreciboinscripcionDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public PagoreciboinscripcionDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    @Transactional(readOnly = true)
    public PagoreciboinscripcionDTO findCurrentByIdAspirante(Integer idAspirante) {
        var entity = repository
                .findFirstByPago_IdAspiranteAndEstado_TipoIgnoreCaseAndEstado_EntidadIgnoreCaseOrderByIdDesc(
                        idAspirante, "EN CURSO", "pagoinscripcion");
        if (entity == null) {
            return null;
        }
        return entityToDto(entity);
    }

    @Transactional(readOnly = true)
    public PagoreciboinscripcionDTO findLastRejectedByIdAspirante(Integer idAspirante) {
        var entity = repository
                .findFirstByPago_IdAspiranteAndEstado_TipoIgnoreCaseAndEstado_EntidadIgnoreCaseOrderByIdDesc(
                        idAspirante, "RECHAZADO", "pagoinscripcion");
        return entityToDto(entity);
    }

    @Transactional(readOnly = true)
    public PagoreciboinscripcionDTO findLastByIdAspirante(Integer idAspirante) {
        var entity = repository.findFirstByPago_IdAspiranteOrderByIdDesc(idAspirante).orElse(null);
        return entityToDto(entity);
    }

    @Transactional(readOnly = true)
    public boolean existsCurrentByIdAspirante(Integer idAspirante) {
        return repository.existsByPago_IdAspiranteAndEstado_TipoIgnoreCaseAndEstado_EntidadIgnoreCase(idAspirante,
                "EN CURSO", "pagoinscripcion");
    }

    public PagoreciboinscripcionDTO create(PagoreciboinscripcionDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public PagoreciboinscripcionDTO update(Integer id, PagoreciboinscripcionDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Pagoreciboinscripcion no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    @Transactional(readOnly = true)
    public List<PagoreciboinscripcionDTO> findByProgramaId(Integer programaId) {
        return entityListToDtoList(repository.findByProgramaIdWithJoins(programaId));
    }

    @Transactional(readOnly = true)
    public List<ufps.edu.co.rest.dto.PagoreciboDirectorProjectionDTO> findDirectorByProgramaId(Integer programaId) {
        return repository.findDirectorByProgramaId(programaId);
    }

    @Transactional(readOnly = true)
    public org.springframework.data.domain.Page<ufps.edu.co.rest.dto.PagoreciboDirectorProjectionDTO> findDirectorByProgramaId(
            Integer programaId, org.springframework.data.domain.Pageable pageable) {
        return repository.findDirectorByProgramaId(programaId, pageable);
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Pagoreciboinscripcion no encontrado con id: " + id));
        repository.deleteById(id);
    }
}