/*
 * Created on 2026-05-30 ( 22:06:14 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.PagorecibomatriculaEntity;
import ufps.edu.co.persistence.repositories.PagorecibomatriculaRepository;
import ufps.edu.co.rest.dto.PagorecibomatriculaDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Pagorecibomatricula" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class PagorecibomatriculaService extends GenericService<PagorecibomatriculaEntity, PagorecibomatriculaDTO> {

    @Autowired
    private PagorecibomatriculaRepository repository;

    public PagorecibomatriculaService() {
        super(PagorecibomatriculaEntity.class, PagorecibomatriculaDTO.class);
    }

    @Transactional(readOnly = true)
    public List<PagorecibomatriculaDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public PagorecibomatriculaDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    @Transactional(readOnly = true)
    public PagorecibomatriculaDTO findCurrentByIdAspirante(Integer idAspirante) {
        var entity = repository
            .findFirstByPago_IdAspiranteAndEstado_TipoIgnoreCaseAndEstado_EntidadIgnoreCaseOrderByIdDesc(
                idAspirante, "EN CURSO", "pagomatricula");
        if (entity == null) {
            return null;
        }
        return entityToDto(entity);
    }

    @Transactional(readOnly = true)
    public boolean existsCurrentByIdAspirante(Integer idAspirante) {
        return repository.existsByPago_IdAspiranteAndEstado_TipoIgnoreCaseAndEstado_EntidadIgnoreCase(idAspirante,
                "EN CURSO", "pagomatricula");
    }

    public PagorecibomatriculaDTO create(PagorecibomatriculaDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public PagorecibomatriculaDTO update(Integer id, PagorecibomatriculaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Pagorecibomatricula no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    @Transactional(readOnly = true)
    public List<PagorecibomatriculaDTO> findByProgramaId(Integer programaId) {
        return entityListToDtoList(repository.findByProgramaIdWithJoins(programaId));
    }

    @Transactional(readOnly = true)
    public List<ufps.edu.co.rest.dto.PagoreciboDirectorProjectionDTO> findDirectorByProgramaId(Integer programaId) {
        return repository.findDirectorByProgramaId(programaId);
    }

    @Transactional(readOnly = true)
    public org.springframework.data.domain.Page<ufps.edu.co.rest.dto.PagoreciboDirectorProjectionDTO> findDirectorByProgramaId(Integer programaId, org.springframework.data.domain.Pageable pageable) {
        return repository.findDirectorByProgramaId(programaId, pageable);
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Pagorecibomatricula no encontrado con id: " + id));
        repository.deleteById(id);
    }
}