/*
 * Created on 2026-05-18 ( 01:57:53 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.PaisEntity;
import ufps.edu.co.persistence.repositories.PaisRepository;
import ufps.edu.co.rest.dto.PaisDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Pais" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class PaisService extends GenericService<PaisEntity, PaisDTO> {

    @Autowired
    private PaisRepository repository;

    public PaisService() {
        super(PaisEntity.class, PaisDTO.class);
    }

    @Transactional(readOnly = true)
    public List<PaisDTO> findAll() {
        // Build DTOs manually to avoid ModelMapper mapping cycles (departamento -> pais -> ...)
        return repository.findAll().stream().map(entity -> {
            PaisDTO dto = new PaisDTO();
            dto.setId(entity.getId());
            dto.setNombre(entity.getNombre());
            return dto;
        }).toList();
    }

    @Transactional(readOnly = true)
    public PaisDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public PaisDTO create(PaisDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public PaisDTO update(Integer id, PaisDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Pais no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Pais no encontrado con id: " + id));
        repository.deleteById(id);
    }
}