/*
 * Created on 2026-05-18 ( 01:57:53 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.PersonaEntity;
import ufps.edu.co.persistence.repositories.PersonaRepository;
import ufps.edu.co.rest.dto.PersonaDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Persona" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class PersonaService extends GenericService<PersonaEntity, PersonaDTO> {

    @Autowired
    private PersonaRepository repository;

    public PersonaService() {
        super(PersonaEntity.class, PersonaDTO.class);
    }

    @Transactional(readOnly = true)
    public List<PersonaDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public PersonaDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public PersonaDTO create(PersonaDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public PersonaDTO update(Integer id, PersonaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Persona no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    /**
     * Update only the correo field of a Persona entity to avoid touching other
     * relationships that can cause transient reference issues.
     */
    public void updateCorreo(Integer id, String correo) {
        PersonaEntity entity = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Persona no encontrado con id: " + id));
        entity.setCorreo(correo);
        repository.save(entity);
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Persona no encontrado con id: " + id));
        repository.deleteById(id);
    }
}