/*
 * Created on 2026-05-18 ( 01:57:54 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.ProgramaEntity;
import ufps.edu.co.persistence.repositories.ProgramaRepository;
import ufps.edu.co.rest.dto.FacultadDTO;
import ufps.edu.co.rest.dto.MunicipioDTO;
import ufps.edu.co.rest.dto.OtrosvaloresDTO;
import ufps.edu.co.rest.dto.ProgramaDTO;
import ufps.edu.co.rest.dto.SedeDTO;
import ufps.edu.co.rest.dto.TiporegistroDTO;
import ufps.edu.co.rest.dto.UbicacionDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Programa" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class ProgramaService extends GenericService<ProgramaEntity, ProgramaDTO> {

    @Autowired
    private ProgramaRepository repository;

    public ProgramaService() {
        super(ProgramaEntity.class, ProgramaDTO.class);
    }

    @Override
    protected ProgramaDTO entityToDto(ProgramaEntity e) {
        FacultadDTO facultadDto = e.getFacultad() != null ? FacultadDTO.builder()
                .id(e.getFacultad().getId())
                .nombre(e.getFacultad().getNombre())
                .correo(e.getFacultad().getCorreo())
                .build() : null;
        MunicipioDTO municipioDto = e.getSede() != null
                && e.getSede().getUbicacion() != null
                && e.getSede().getUbicacion().getMunicipio() != null
                ? MunicipioDTO.builder()
                        .id(e.getSede().getUbicacion().getMunicipio().getId())
                        .nombre(e.getSede().getUbicacion().getMunicipio().getNombre())
                        .idDepartamento(e.getSede().getUbicacion().getMunicipio().getIdDepartamento())
                        .build() : null;
        UbicacionDTO ubicacionDto = e.getSede() != null && e.getSede().getUbicacion() != null ? UbicacionDTO.builder()
                .id(e.getSede().getUbicacion().getId())
                .direccion(e.getSede().getUbicacion().getDireccion())
                .idMunicipio(e.getSede().getUbicacion().getIdMunicipio())
                .municipio(municipioDto)
                .build() : null;
        SedeDTO sedeDto = e.getSede() != null ? SedeDTO.builder()
                .id(e.getSede().getId())
                .nombre(e.getSede().getNombre())
                .idUbicacion(e.getSede().getIdUbicacion())
                .ubicacion(ubicacionDto)
                .build() : null;
        OtrosvaloresDTO otrosDto = e.getOtrosvalores() != null ? OtrosvaloresDTO.builder()
                .id(e.getOtrosvalores().getId())
                .carnet(e.getOtrosvalores().getCarnet())
                .estampilla(e.getOtrosvalores().getEstampilla())
                .seguro(e.getOtrosvalores().getSeguro())
                .build() : null;
        TiporegistroDTO tiporegistroDto = e.getTiporegistro() != null ? TiporegistroDTO.builder()
                .id(e.getTiporegistro().getId())
                .tipo(e.getTiporegistro().getTipo())
                .build() : null;
        return ProgramaDTO.builder()
                .id(e.getId())
                .codigo(e.getCodigo())
                .nombre(e.getNombre())
                .duracion(e.getDuracion())
                .correo(e.getCorreo())
                .registrosnies(e.getRegistrosnies())
                .nivelformacion(e.getNivelformacion())
                .titulo(e.getTitulo())
                .rcmineducacion(e.getRcmineducacion())
                .creditos(e.getCreditos())
                .periodicidad(e.getPeriodicidad())
                .valormatricula(e.getValormatricula())
                .idFacultad(e.getIdFacultad())
                .idOtros(e.getIdOtros())
                .idSede(e.getIdSede())
                .idTiporegistro(e.getIdTiporegistro())
                .idModalidad(e.getIdModalidad())
                .facultad(facultadDto)
                .sede(sedeDto)
                .otrosvalores(otrosDto)
                .tiporegistro(tiporegistroDto)
                .build();
    }

    @Transactional(readOnly = true)
    public List<ProgramaDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public ProgramaDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    @Transactional(readOnly = true)
    public List<ProgramaDTO> findByIdFacultad(Integer idFacultad) {
        return entityListToDtoList(repository.findByIdFacultad(idFacultad));
    }

    public ProgramaDTO create(ProgramaDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public ProgramaDTO update(Integer id, ProgramaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Programa no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Programa no encontrado con id: " + id));
        repository.deleteById(id);
    }
}
